/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcbspay_platform_jni_YHT_JNI */

#ifndef _Included_com_zcbspay_platform_jni_YHT_JNI
#define _Included_com_zcbspay_platform_jni_YHT_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcbspay_platform_jni_YHT_JNI
 * Method:    sendYHTBWFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zcbspay_platform_jni_YHT_1JNI_sendYHTBWFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_zcbspay_platform_jni_YHT_JNI
 * Method:    recvYHTBWFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zcbspay_platform_jni_YHT_1JNI_recvYHTBWFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
